[package]
name = "tree-sitter-vimdoc"
description = "Vimdoc grammar for the tree-sitter parsing library"
version = "2.1.0"
keywords = ["incremental", "parsing", "neovim", "vimdoc"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/neovim/tree-sitter-vimdoc"
edition = "2018"
license = "Apache-2.0"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20.8"

[build-dependencies]
cc = "1.0"
